# Build and run udpspoofer with libpcap available
FROM golang:1.25-alpine AS build
RUN apk add --no-cache build-base libpcap-dev
WORKDIR /app
COPY go.mod .
COPY go.sum .
COPY ./docker/entrypoint-udpspoofer-testing.sh .
RUN go mod download
COPY .. .
# CGO is required for libpcap
RUN CGO_ENABLED=1 go build -o udpspoofer ./cmd/udpspoofer

FROM alpine:3.20
RUN apk add --no-cache libpcap iptables tcpdump
WORKDIR /app
COPY --from=build /app/udpspoofer /app/udpspoofer
COPY --from=build /app/entrypoint-udpspoofer-testing.sh .

# .env will be mounted by docker-compose (docker.env -> /app/.env)
ENTRYPOINT ["/app/entrypoint-udpspoofer-testing.sh"]