services:
  clickhouse:
    image: clickhouse/clickhouse-server:23.8
    container_name: clickhouse
    environment:
      CLICKHOUSE_USER: "test"
      CLICKHOUSE_PASSWORD: "test"
      CLICKHOUSE_DB: "test"
    ports:
      - "9123:9000"   # native TCP
      - "8123:8123"   # HTTP
    volumes:
      - ../clickhouse_data:/var/lib/clickhouse
      - ../clickhouse/init:/docker-entrypoint-initdb.d:ro
    networks:
      telescope-net:
        aliases:
          - clickhouse

  udpspoofer:
    build:
      context: .
      dockerfile: Dockerfile.udpspoofer
    container_name: udpspoofer
    depends_on:
      - clickhouse
    cap_add:
      - NET_ADMIN
      - NET_RAW
    security_opt:
      - seccomp:unconfined
    volumes:
      - ./docker.env:/app/.env:ro
    networks:
      telescope-net:
        aliases:
          - udpspoofer

  pcap-sender:
    build:
      context: .
      dockerfile: Dockerfile.pcap-sender
    container_name: pcap-sender
    depends_on:
      - udpspoofer
    cap_add:
      - NET_ADMIN
      - NET_RAW
    security_opt:
      - seccomp:unconfined
    volumes:
      - ../testdata/input.pcap:/pcap/input.pcap:ro
    networks:
      telescope-net:

volumes:
  clickhouse_data:

networks:
  telescope-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.25.0.0/16